name: 12H Live Stream
on:
  push:
    branches:
      - main  # උඹේ branch එකේ නම වෙනස් නම් ඒක දාපන් (උදා: master)
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: sudo apt update && sudo apt install ffmpeg jq -y
      - name: Run Script
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: python3 main.py
